#!/bin/bash

set -o errexit
set -o nounset

VERSION="$(git describe --tags --always --dirty)"
LDFLAGS="-X main.VersionString=$VERSION -X main.RevisionString=$(git rev-parse --sq HEAD)"

gox -ldflags "$LDFLAGS" -os 'linux windows darwin' -arch '386 amd64' -output 'dist/{{.OS}}_{{.Arch}}/{{.Dir}}' $(go list ./... | grep -v '/vendor/')

find dist/* -type d -exec tar cvzf {}.tar.gz -C {} . \;
