#!/bin/bash

set -o errexit
set -o nounset

gox -os 'linux windows darwin' -arch '386 amd64' -output 'dist/{{.OS}}_{{.Arch}}/{{.Dir}}' git-duet/...

for build in $(find dist/* -type d) ; do tar cvzf $build.tar.gz -C $build . ; done
